"""empty message

Revision ID: 257aba69afea
Revises: 
Create Date: 2019-12-03 23:36:02.441945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257aba69afea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safe_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('filetypes', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('md5'),
    sa.UniqueConstraint('sha1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safe_files')
    # ### end Alembic commands ###
