"""empty message

Revision ID: 69e63cfd3c09
Revises: f6dac5277df9
Create Date: 2019-12-03 15:01:00.775637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e63cfd3c09'
down_revision = 'f6dac5277df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safe_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('filetypes', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('md5'),
    sa.UniqueConstraint('sha1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safe_files')
    # ### end Alembic commands ###
